In [16]:
from math import pow
from math import log
from math import factorial
import random
import time
from statistics import mean
import matplotlib.pyplot as plt
import numpy as np

In [17]:
def backward_substitution(L, b):
    x = np.zeros_like(b)
    for i in range(len(A)-1, 0, -1):
        s = 0
        for j in range(i-1, 0, -1):
            s += L[j, i]*x[i]
        x[i] = ((b[i]-s)/L[i, i])
    return x

In [18]:
def forward_substitution(L, b):
    x = np.zeros_like(b)
    for i in range(len(L)):
        s = 0
        for j in range(i):
            s += L[i, j]*x[j]
        x[i] = (b[i]-s)/L[i, i]
    return x

In [21]:
A = np.array([[1, 0, 0], [-1, 2, 0], [0, -3, 4]])
A2 = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
b = [2, 4, 3]
print(backward_substitution(A2, b))
print(forward_substitution(A, b))

[0 2 1]
[2 3 3]


In [5]:
def random_lower_triangular_matrix(m, n, random_range = (1, 10)):
    A = []
    for i in range(m):
        wiersz = []
        for j in range(n):
            if i<=j:
                wiersz.append(random.randint(random_range[0], random_range[1]))
            else:
                wiersz.append(0)
        A.append(wiersz)
    return np.array(A)

In [6]:
A = random_lower_triangular_matrix(3, 3)
print(A)
b = [2, 4, 3]
forward_substitution(A, b)

[[3 7 5]
 [0 7 3]
 [0 0 6]]


array([0, 0, 0])

In [7]:
def Gaussian_elimination(A, b):
    if np.shape(A)[0] == np.shape(A)[1]:
        x = 0
    return x

In [8]:
A = np.array([[1, 0, 0], [-1, 2, 0], [0, -3, 4]])
