In [1]:
import numpy as np

In [2]:
def gram_schmidt(A):
    n = A.shape[1]
    Q = np.zeros_like(A, dtype=float)
    for i in range(n):
        qi = A[:,i]
        for j in range(i):
            proj = np.dot(A[:,i], Q[:,j]) * Q[:,j]
            qi = qi - proj
        Q[:,i] = qi / np.linalg.norm(qi)
    return Q

In [3]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,1]])
print('A\n', A)

Q = gram_schmidt(A)
print('Wynik kodu:\n', Q)
print('Wartości iloczynów skalarnych i norm:\n', Q.T@Q)

A
 [[1 2 3]
 [4 5 6]
 [7 8 1]]
Wynik kodu:
 [[ 0.12309149  0.90453403 -0.40824829]
 [ 0.49236596  0.30151134  0.81649658]
 [ 0.86164044 -0.30151134 -0.40824829]]
Wartości iloczynów skalarnych i norm:
 [[ 1.00000000e+00  1.45860311e-15 -1.88712020e-15]
 [ 1.45860311e-15  1.00000000e+00 -1.80126295e-15]
 [-1.88712020e-15 -1.80126295e-15  1.00000000e+00]]


In [4]:
def random_matrices(columns, rows, quantity=1):
    result = []
    for i in range(quantity):
        result.append(np.random.rand(rows, columns))
    return np.array(result)

In [5]:
n = 1000
dim_max = 10
i = 0
for dim in range(1, dim_max+1):
    for B in random_matrices(dim, dim, n):
        array = np.matmul(B, B.T)
        result = gram_schmidt(array)
        if np.all(np.isclose(result.T@result, np.identity(dim)) == True):
            i+=1
        #else:
            #print('array', array, '\nwynik funkcji\n', result.T@result)
print('Otrzymano', i, 'poprawnych wyników na', n*dim_max, 'testów.')

Otrzymano 9876 poprawnych wyników na 10000 testów.
