In [1]:
import numpy as np

In [2]:
def gram_schmidt(A):
    n = A.shape[1]
    Q = np.zeros_like(A, dtype=float)
    for i in range(n):
        qi = A[:,i]
        for j in range(i):
            proj = np.dot(A[:,i], Q[:,j]) * Q[:,j]
            qi = qi - proj
        Q[:,i] = qi / np.linalg.norm(qi)
    return Q

In [3]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,1]])
print('A\n', A)

Q = gram_schmidt(A)
print('Wynik kodu:\n', Q)
print('Wartości iloczynów skalarnych i norm:\n', Q.T@Q)

A
 [[1 2 3]
 [4 5 6]
 [7 8 1]]
Wynik kodu:
 [[ 0.12309149  0.90453403 -0.40824829]
 [ 0.49236596  0.30151134  0.81649658]
 [ 0.86164044 -0.30151134 -0.40824829]]
Wartości iloczynów skalarnych i norm:
 [[ 1.00000000e+00  1.45860311e-15 -1.88712020e-15]
 [ 1.45860311e-15  1.00000000e+00 -1.80126295e-15]
 [-1.88712020e-15 -1.80126295e-15  1.00000000e+00]]


In [4]:
def random_matrices(columns, rows, quantity=1):
    result = []
    for i in range(quantity):
        result.append(np.random.rand(rows, columns))
    return np.array(result)

In [6]:
n = 1000
dim_max = 10
i = 0
for dim in range(1, dim_max+1):
    for B in random_matrices(dim, dim, n):
        array = np.matmul(B, B.T)
        result = gram_schmidt(array)
        if np.all(np.isclose(result.T@result, np.identity(dim)) == True):
            i+=1
        else:
            print('array', array, '\nwynik funkcji\n', result.T@result)
print('Otrzymano', i, 'poprawnych wyników na', n*dim_max, 'testów.')

array [[0.51706292 0.75738738 0.50168855 0.75920327]
 [0.75738738 1.30984972 0.92135006 1.34917547]
 [0.50168855 0.92135006 0.96499794 1.3552883 ]
 [0.75920327 1.34917547 1.3552883  1.91520322]] 
wynik funkcji
 [[ 1.00000000e+00  2.64756105e-15 -2.23505831e-15  3.07867117e-10]
 [ 2.64756105e-15  1.00000000e+00 -1.86588967e-14 -1.20683700e-09]
 [-2.23505831e-15 -1.86588967e-14  1.00000000e+00  2.70213902e-08]
 [ 3.07867117e-10 -1.20683700e-09  2.70213902e-08  1.00000000e+00]]
array [[0.69324153 0.55187427 0.17178274 0.97757362]
 [0.55187427 0.50143687 0.19268628 0.8744353 ]
 [0.17178274 0.19268628 0.20924982 0.54929884]
 [0.97757362 0.8744353  0.54929884 1.94526004]] 
wynik funkcji
 [[ 1.00000000e+00 -3.37644515e-15  4.97612168e-15 -2.28787976e-08]
 [-3.37644515e-15  1.00000000e+00  1.66957877e-14  1.69220878e-07]
 [ 4.97612168e-15  1.66957877e-14  1.00000000e+00 -7.03224109e-07]
 [-2.28787976e-08  1.69220878e-07 -7.03224109e-07  1.00000000e+00]]
array [[1.0022444  1.65159981 1.1061687 

array [[2.15428676 1.65005802 1.38201018 0.68827218 0.9336649 ]
 [1.65005802 1.63329616 1.51793033 0.79147515 1.02476653]
 [1.38201018 1.51793033 1.54393799 0.92354346 1.0866619 ]
 [0.68827218 0.79147515 0.92354346 0.69824756 0.70098969]
 [0.9336649  1.02476653 1.0866619  0.70098969 0.786886  ]] 
wynik funkcji
 [[ 1.00000000e+00  1.18236244e-15 -7.87369082e-15  1.30874633e-13
   1.48329672e-11]
 [ 1.18236244e-15  1.00000000e+00 -2.60622896e-14  4.37360648e-13
   3.22098772e-11]
 [-7.87369082e-15 -2.60622896e-14  1.00000000e+00  2.66051817e-12
   4.78895587e-10]
 [ 1.30874633e-13  4.37360648e-13  2.66051817e-12  1.00000000e+00
  -1.31452313e-08]
 [ 1.48329672e-11  3.22098772e-11  4.78895587e-10 -1.31452313e-08
   1.00000000e+00]]
array [[2.53725413 1.62928192 2.37985212 1.90418668 2.53176709 2.02415566]
 [1.62928192 2.12062329 1.55505517 1.39471457 1.58030865 1.27229464]
 [2.37985212 1.55505517 2.38454537 1.77219596 2.26638434 1.95200994]
 [1.90418668 1.39471457 1.77219596 1.94622889 2.

array [[1.1483592  0.89906819 1.93344114 1.65645028 1.21427648 1.35612289
  1.57645585]
 [0.89906819 1.7964568  2.41157939 2.0554555  1.38726862 2.22613672
  1.15364223]
 [1.93344114 2.41157939 4.51843436 3.40106365 2.83923012 3.48631394
  3.06473473]
 [1.65645028 2.0554555  3.40106365 3.00361908 1.88471062 2.72792285
  2.11252845]
 [1.21427648 1.38726862 2.83923012 1.88471062 2.39142226 2.26364955
  2.09367888]
 [1.35612289 2.22613672 3.48631394 2.72792285 2.26364955 3.04116198
  2.06702626]
 [1.57645585 1.15364223 3.06473473 2.11252845 2.09367888 2.06702626
  2.91786528]] 
wynik funkcji
 [[ 1.00000000e+00 -3.48291029e-16  9.08143638e-16 -7.00115801e-16
  -6.48909588e-15  1.96880822e-14 -7.89367468e-11]
 [-3.48291029e-16  1.00000000e+00  5.99847449e-15  2.45681677e-14
   3.56195591e-14  5.25936062e-14  5.37766277e-11]
 [ 9.08143638e-16  5.99847449e-15  1.00000000e+00 -9.30306489e-14
  -2.21498267e-13 -4.35195787e-13 -3.02534015e-10]
 [-7.00115801e-16  2.45681677e-14 -9.30306489e-14  1

array [[1.22123753 1.46637859 1.78297302 1.31234226 0.78604014 0.63103914
  1.21843919 1.53489675]
 [1.46637859 4.148585   3.97493303 2.72672868 2.32054475 2.5590107
  2.78223404 3.36001068]
 [1.78297302 3.97493303 4.16601125 2.74892321 2.24823483 2.17590461
  2.6994776  3.29988971]
 [1.31234226 2.72672868 2.74892321 2.32868218 1.57859847 1.44312988
  1.75957942 2.33948246]
 [0.78604014 2.32054475 2.24823483 1.57859847 1.60515806 1.59819383
  1.31786721 1.6152888 ]
 [0.63103914 2.5590107  2.17590461 1.44312988 1.59819383 2.27823516
  2.00862169 1.96626905]
 [1.21843919 2.78223404 2.6994776  1.75957942 1.31786721 2.00862169
  2.78903513 2.5796944 ]
 [1.53489675 3.36001068 3.29988971 2.33948246 1.6152888  1.96626905
  2.5796944  3.28212906]] 
wynik funkcji
 [[ 1.00000000e+00 -1.19062167e-15 -3.50094635e-16 -9.80894903e-16
  -8.74640082e-16  4.28951207e-15 -4.29968023e-14 -9.70172457e-11]
 [-1.19062167e-15  1.00000000e+00  3.85620904e-14  1.39688440e-14
  -1.59170732e-14  1.54533316e-13 -

array [[2.68809292 1.39290092 1.82139955 2.28088072 1.50252595 3.30845225
  1.66303687 2.36736557]
 [1.39290092 1.5794735  1.31093817 1.77155332 0.72949577 2.29219271
  1.12385423 1.20032876]
 [1.82139955 1.31093817 2.72131974 2.0636403  1.81932406 3.43585878
  2.2658369  2.20668843]
 [2.28088072 1.77155332 2.0636403  2.61786475 1.36151841 3.27797116
  1.73067113 2.18176676]
 [1.50252595 0.72949577 1.81932406 1.36151841 1.65501488 2.53331325
  1.91977514 1.82567709]
 [3.30845225 2.29219271 3.43585878 3.27797116 2.53331325 5.62109747
  3.15688545 3.72681123]
 [1.66303687 1.12385423 2.2658369  1.73067113 1.91977514 3.15688545
  2.45191596 2.25492648]
 [2.36736557 1.20032876 2.20668843 2.18176676 1.82567709 3.72681123
  2.25492648 3.04794708]] 
wynik funkcji
 [[ 1.00000000e+00 -1.28496910e-17 -1.05932119e-16 -1.15719277e-15
  -1.35632179e-15 -2.54898027e-15  4.78820673e-15  2.35839034e-09]
 [-1.28496910e-17  1.00000000e+00  1.47665861e-16 -1.31539125e-15
  -1.89902497e-15 -1.46463647e-15 

array [[3.02191689 2.4435174  3.72860958 2.28134951 1.90752925 1.82147996
  1.37968572 2.50167742 2.09360987]
 [2.4435174  2.63789009 3.48080193 1.81754611 1.72582551 1.39394956
  0.91402608 1.62640401 2.41496097]
 [3.72860958 3.48080193 5.87423839 2.98278662 3.0049279  2.5817177
  2.21343205 3.23976353 3.64237866]
 [2.28134951 1.81754611 2.98278662 2.27953392 1.69371359 1.28866399
  1.00629055 1.94959767 1.08490796]
 [1.90752925 1.72582551 3.0049279  1.69371359 2.15369627 1.25325423
  1.39710252 1.58342901 1.73394447]
 [1.82147996 1.39394956 2.5817177  1.28866399 1.25325423 1.42182264
  1.10191926 1.70314429 1.57056354]
 [1.37968572 0.91402608 2.21343205 1.00629055 1.39710252 1.10191926
  1.57482081 1.54838301 1.36009102]
 [2.50167742 1.62640401 3.23976353 1.94959767 1.58342901 1.70314429
  1.54838301 2.96151384 1.89199076]
 [2.09360987 2.41496097 3.64237866 1.08490796 1.73394447 1.57056354
  1.36009102 1.89199076 3.44036621]] 
wynik funkcji
 [[ 1.00000000e+00  9.03229397e-16 -2.84282

   1.88457616e-07  1.00000000e+00]]
array [[4.45639426 3.24828093 3.32295686 3.21952166 3.59844525 3.1337891
  2.43126286 3.79697664 1.06672793 3.33289721]
 [3.24828093 3.49864224 2.73960926 2.80943839 2.85212729 3.15843462
  2.51120085 3.59792028 1.56693533 2.7671837 ]
 [3.32295686 2.73960926 3.29864264 2.35412465 3.0794679  2.87170173
  2.4658865  3.04668109 0.92222046 2.29328989]
 [3.21952166 2.80943839 2.35412465 3.73750445 2.48909476 2.24544978
  2.35500269 3.39445187 1.44781706 2.77715124]
 [3.59844525 2.85212729 3.0794679  2.48909476 3.49790794 3.36627972
  2.54291361 3.35473146 1.10762401 2.94600711]
 [3.1337891  3.15843462 2.87170173 2.24544978 3.36627972 4.03838845
  2.77357882 3.52783973 1.42717026 2.8995448 ]
 [2.43126286 2.51120085 2.4658865  2.35500269 2.54291361 2.77357882
  2.96064599 2.94674305 1.5234472  2.04113404]
 [3.79697664 3.59792028 3.04668109 3.39445187 3.35473146 3.52783973
  2.94674305 4.30727008 1.84293296 3.40410262]
 [1.06672793 1.56693533 0.92222046 1.44

  -3.06127335e-06  1.00000000e+00]]
array [[2.47018609 1.82041925 2.17579014 1.80790291 2.91672153 2.17309441
  2.49137159 2.01000231 2.52015361 3.18447811]
 [1.82041925 3.00769664 3.26440314 2.22856321 3.07556671 2.90402964
  2.82018425 2.89376619 3.75942454 2.67240669]
 [2.17579014 3.26440314 4.18290457 2.43429137 3.54274438 3.58739788
  2.87998236 3.10545198 4.24509343 3.34710936]
 [1.80790291 2.22856321 2.43429137 2.22735668 2.92063375 2.21793606
  2.48257843 2.09910193 2.927634   2.41834946]
 [2.91672153 3.07556671 3.54274438 2.92063375 4.62999176 3.35750814
  3.66635606 2.94055948 4.1822186  3.90707495]
 [2.17309441 2.90402964 3.58739788 2.21793606 3.35750814 3.34844357
  3.0433     2.95184004 3.60715989 3.2138198 ]
 [2.49137159 2.82018425 2.87998236 2.48257843 3.66635606 3.0433
  3.92646167 2.9931832  3.44326687 3.34384342]
 [2.01000231 2.89376619 3.10545198 2.09910193 2.94055948 2.95184004
  2.9931832  3.53825067 3.74333124 3.13654258]
 [2.52015361 3.75942454 4.24509343 2.92763