In [24]:
import numpy as np

In [2]:
def pure_divide(a, b, eps = 2**(-16)):
    if abs(b) <eps:
        return (0, 1)
    else:
        return (a/b, 0)

In [3]:
def pure_sqrt(a):
    if a<0:
        return (0, 1)
    else:
        return (np.sqrt(a), 0)

In [17]:
def cholesky(A):
    L=np.full_like(A, 0, dtype=float)
    n = len(L)
    for j in range(n):
        for i in range(j, n):
            if i == j:
                suma = 0
                for k in range(i):
                    suma += L[i, k]**2
                if A[i, j]-suma<0:
                    print('Macierz nie jest dodatnio określona.')
                    return 0
                L[i, j] = np.sqrt(A[i, j]-suma)
            else:
                suma2 = 0
                for k in range(j):
                    suma2 += L[i, k]*L[j, k]
                L[i, j] = (A[i, j]-suma2)/L[j, j]
    return L

In [5]:
def pure_cholesky(A):
    L=np.full_like(A, 0, dtype=float)
    n = len(L)
    for j in range(n):
        for i in range(j, n):
            if i == j:
                suma = 0
                for k in range(i):
                    suma += L[i, k]**2
                pure = pure_sqrt(A[i, j]-suma)
                if pure[1] == 1:
                    print('Macierz nie jest dodatnio określona.')
                    return 0
                L[i, j] = pure[0]
            else:
                suma2 = 0
                for k in range(j):
                    suma2 += L[i, k]*L[j, k]
                pure = pure_divide(A[i, j]-suma2, L[j, j])
                if pure[1] == 1:
                    print('Błąd przy próbie dzielenia.')
                    return 0
                L[i, j] = pure[0]
    return L

In [6]:
A = np.array([[1, 2, 3],
              [2, 5, 6],
              [3, 6, 10]])
print('macierz A:\n', A)
L = pure_cholesky(A)
print('pierwiastek tej macierzy to\n', L)
print('numpy wynik\n:', np.linalg.cholesky(A))
print('czy zgadza sie iloczyn z transpozycją?\n', np.matmul(L, L.T))

macierz A:
 [[ 1  2  3]
 [ 2  5  6]
 [ 3  6 10]]
pierwiastek tej macierzy to
 [[1. 0. 0.]
 [2. 1. 0.]
 [3. 0. 1.]]
numpy wynik
: [[1. 0. 0.]
 [2. 1. 0.]
 [3. 0. 1.]]
czy zgadza sie iloczyn z transpozycją?
 [[ 1.  2.  3.]
 [ 2.  5.  6.]
 [ 3.  6. 10.]]


In [7]:
def random_matrices(columns, rows, quantity=1):
    result = []
    for i in range(quantity):
        result.append(np.random.rand(rows, columns))
    return np.array(result)

In [25]:
n = 1000
dim_max = 10
i = 0
for dim in range(1, dim_max+1):
    for B in random_matrices(dim, dim, n):
        array = np.matmul(B, B.T)
        if np.all(np.isclose(cholesky(array), np.linalg.cholesky(array)) == True):
            i+=1
        #else:
            #print('array', array, '\nwynik funkcji\n', cholesky(array), '\nwynik numpy\n', np.linalg.cholesky(array))
print('Otrzymano', i, 'poprawnych wyników na', n*dim_max, 'testów.')

Otrzymano 10000 poprawnych wyników na 10000 testów.


In [41]:
def gram_schmidt(A):
    n = A.shape[1]
    Q = np.zeros_like(A, dtype=float)
    for k in range(n):
        qk = A[:,k]
        print('k=', k, 'qk', qk)
        for i in range(k):
            qk = qk - np.dot(A[:,k],Q[:,i]) * Q[:,i]
            print('i=', i, 'iloczyn skalarny', np.dot(A[:,k],Q[:,i]), 'i ty wektor z Q', Q[:,i])
        qk = qk/np.sqrt(np.dot(qk,qk))
        Q[:,k] = qk
        print('qk, Q:', qk,'\n', Q)
    return Q  

In [42]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,10]])
print('A\n', A)

Q = gram_schmidt(A)
print('Q\n', Q)

print('iloczyn transpozycji', Q.T @ Q)

A
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
k= 0 qk [1 4 7]
qk, Q: [0.12309149 0.49236596 0.86164044] 
 [[0.12309149 0.         0.        ]
 [0.49236596 0.         0.        ]
 [0.86164044 0.         0.        ]]
k= 1 qk [2 5 8]
i= 0 iloczyn skalarny 9.601136296387953 i ty wektor z Q [0.12309149 0.49236596 0.86164044]
qk, Q: [ 0.90453403  0.30151134 -0.30151134] 
 [[ 0.12309149  0.90453403  0.        ]
 [ 0.49236596  0.30151134  0.        ]
 [ 0.86164044 -0.30151134  0.        ]]
k= 2 qk [ 3  6 10]
i= 0 iloczyn skalarny 11.939874624995273 i ty wektor z Q [0.12309149 0.49236596 0.86164044]
i= 1 iloczyn skalarny 1.5075567228888356 i ty wektor z Q [ 0.90453403  0.30151134 -0.30151134]
qk, Q: [ 0.40824829 -0.81649658  0.40824829] 
 [[ 0.12309149  0.90453403  0.40824829]
 [ 0.49236596  0.30151134 -0.81649658]
 [ 0.86164044 -0.30151134  0.40824829]]
Q
 [[ 0.12309149  0.90453403  0.40824829]
 [ 0.49236596  0.30151134 -0.81649658]
 [ 0.86164044 -0.30151134  0.40824829]]
iloczyn transpozycji [[ 1.0