In [71]:
import numpy as np
import math

ModuleNotFoundError: No module named 'linalg'

In [103]:
def pure_devide(a, b, is_zero):
    if is_zero:
        return 0
    else:
        return 1
        

In [108]:
def Cholesky(A):
    L=np.full_like(A, 0)
    n = len(L)
    for j in range(n):
        for i in range(j, n):
            if i == j:
                suma = 0
                for k in range(i):
                    suma += L[i, k]**2
                try:
                    L[i, j] = math.sqrt(A[i, j]-suma)#-L[i, 0]**2
                except:
                    print('macierz nie jest dodatnio określona.')
                    return 'blad'
            else:
                suma2 = 0
                for k in range(j):
                    suma2 += L[i, k]*L[j, k]
                L[i, j] = (A[i, j]-suma2)/L[j, j]
    return L

In [111]:
A = np.array([[1, 2, 3], [2, 5, 6], [3, 6, 10]])
print('macierz A:\n', A)
L = Cholesky(A)
print('pierwiastek tej macierzy to\n', L)
print('numpy wynik\n:', np.linalg.cholesky(A))
print('czy zgadza sie macierz?\n', np.matmul(L, L.T))

macierz A:
 [[ 1  2  3]
 [ 2  5  6]
 [ 3  6 10]]
pierwiastek tej macierzy to
 [[1 0 0]
 [2 1 0]
 [3 0 1]]
numpy wynik
: [[1. 0. 0.]
 [2. 1. 0.]
 [3. 0. 1.]]
czy zgadza sie macierz?
 [[ 1  2  3]
 [ 2  5  6]
 [ 3  6 10]]


In [112]:
def random_matrices(columns, rows, quantity=1):
    result = []
    for i in range(quantity):
        result.append(np.random.rand(rows, columns))
    return result

In [128]:
n = 100
dim_max = 10
i = 0
for dim in range(1, dim_max):
    for B in random_matrices(dim, dim, n):
        array = np.matmul(B, B.T)
        if np.all(np.equal(Cholesky(array), np.linalg.cholesky(array)) == True):
            i+=1
print('Otrzymano', i, 'błędów na', n, 'testów.')

Otrzymano 233 błędów na 100 testów.
