In [57]:
import numpy as np
import random

def eig(A_original):
    A = A_original.copy().astype(float)
    n = A.shape[0]
    eigenvalues = []
    eigenvectors = np.zeros_like(A)
    max_iter = 100
    mu = np.random.rand()
    v = np.random.rand(n)
    for i in range(n):
        iterations = 0
        mu = np.random.rand()
        while max(abs(A@v-mu*v))>2**(-10) and\
            iterations < max_iter:
            v = np.linalg.solve(A-mu*np.identity(A.shape[0]), v)
            v = v/np.linalg.norm(v)
            mu = v.T@A@v
            iterations += 1
        eigenvectors[:,i] = v
        eigenvalues.append(mu)
    return (eigenvalues, eigenvectors)

Kod:
 [2.8103453360807884, 2.8103453360247825, 2.8103453358474844] 
 [[-0.0922201  -0.09221315 -0.09222677]
 [-0.85329203 -0.85329371 -0.85329056]
 [ 0.51321356  0.51321203  0.51321482]] 
linalg:
 (array([13.27009751, -0.08044285,  2.81034534]), array([[ 0.28122477,  0.95520076, -0.09221791],
       [ 0.47210705, -0.22137446, -0.85329261],
       [ 0.83548044, -0.1964303 ,  0.51321299]]))


In [58]:
A = np.array([[1, 0], [0, 1]])
A = np.array([[1, 2, 3],
              [2, 5, 4],
              [3, 4, 10]])
nasze_values, nasze_wektors = eig(A)

print('Kod:\n', nasze_values, '\n', nasze_wektors, '\nlinalg:\n', np.linalg.eig(A))

Kod:
 [-0.08044285042150333, -0.08044285042150316, -0.08044285042150323] 
 [[-0.95520076  0.95520076 -0.95520076]
 [ 0.22137446 -0.22137446  0.22137446]
 [ 0.1964303  -0.1964303   0.1964303 ]] 
linalg:
 (array([13.27009751, -0.08044285,  2.81034534]), array([[ 0.28122477,  0.95520076, -0.09221791],
       [ 0.47210705, -0.22137446, -0.85329261],
       [ 0.83548044, -0.1964303 ,  0.51321299]]))


In [ ]:
def random_matrices(columns, rows, quantity=1):
    result = []
    for i in range(quantity):
        result.append(np.random.rand(rows, columns))
    return np.array(result)

In [ ]:
n = 1000
dim_max = 10
i = 0
for dim in range(1, dim_max+1):
    for B in random_matrices(dim, dim, n):
        array = np.matmul(B, B.T)
        result = gram_schmidt(array)
        if np.all(np.isclose(result.T@result, np.identity(dim)) == True):
            i+=1
        else:
            print('array', array, '\nwynik funkcji\n', result.T@result)
print('Otrzymano', i, 'poprawnych wyników na', n*dim_max, 'testów.')